In [1]:
import pandas as pd
import numpy as np
import json

- 训练集选择10000个样本，测试集选择1000个样本

# 获取测试集

In [2]:
num_sample = 1000
csv_file_path = 'data/test.csv'
save_path = 'data/test.json'
df = pd.read_csv(csv_file_path)

In [3]:
df.head(3)

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel1016,pixel1017,pixel1018,pixel1019,pixel1020,pixel1021,pixel1022,pixel1023,pixel1024,hash
0,2,0,199,51,23,0,0,227,255,127,...,0,0,0,0,0,0,0,0,0,24ced6eb4c3b6b16e6d911401ca9b9bf
1,6,0,0,4,24,56,93,220,101,80,...,72,142,247,1,247,27,121,109,75,9c9133f89cf857325fd041ca8640d51b
2,9,116,139,255,244,252,137,139,139,255,...,108,73,3,105,85,183,102,171,7,13544f465094166da9ad6f04833c4a7f

In [4]:
data = []
for i in range(num_sample):
    img = df.iloc[i,1:1+1024].to_list()
    img = [int(pixel) for pixel in img]
    label = int(df.iloc[i,0])
    data.append([img, label])

In [5]:
with open(save_path, 'w', encoding='utf8') as f:
    json.dump(data, f)

# 获取训练集

In [6]:
num_sample = 10000
csv_file_path = 'data/train.csv'
save_path = 'data/train.json'
df = pd.read_csv(csv_file_path)

In [7]:
df.head(3)

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel1016,pixel1017,pixel1018,pixel1019,pixel1020,pixel1021,pixel1022,pixel1023,pixel1024,hash
0,3,212,1,77,204,137,117,139,161,199,...,0,0,0,0,0,0,0,0,0,aa527b5aea9fe96fabae78e85ba59491
1,0,0,19,3,233,127,0,70,1,233,...,104,28,233,150,115,173,126,27,64,05597db8265479234c8e15a7290cd7f0
2,1,0,181,232,0,0,141,133,255,221,...,116,223,203,183,56,59,62,50,51,b1375b03e66c56e9a733eaf3d2a5bdbd

In [8]:
data = []
for i in range(num_sample):
    img = df.iloc[i,1:1+1024].to_list()
    img = [int(pixel) for pixel in img]
    label = int(df.iloc[i,0])
    data.append([img, label])

In [9]:
with open(save_path, 'w', encoding='utf8') as f:
    json.dump(data, f)